import type { Metadata, Viewport } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Header } from './components/Header';
import { Footer } from './components/Footer';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const viewport: Viewport = {
	colorScheme: 'light',
};

export const metadata: Metadata = {
	title: 'Underwood',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className='flex flex-col w-full max-w-80 min-w-80 items-stretch mx-auto font-sans '>
					<Header />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
}
